#!/bin/env bash

start_sway_idle() {
  session_lock=120
  suspend=300
  swayidle -w \
    timeout $session_lock 'swaylock -f' \
    timeout $suspend 'systemctl suspend' \
    before-sleep 'pgrep -x swaylock || swaylock -f'
}

# We are doing things in a round-about way here because
# these applications will fail to start if the Wayland compositor is not
# already running when we start them.
do_startup() {
  waybar &
  start_sway_idle &
  pgrep -x mako || mako &

  if [ ! -z "$WALLPAPER_CMD" ]; then
    sh -c "$WALLPAPER_CMD" &
  fi
}
case "$1" in
  startup) do_startup
  ;;
  *) echo default
    "$HOME/repos/dotfiles/src/dwl/dwl" -s "$0 startup" > /tmp/dwl-output 2>> /tmp/dwl-stderr
  ;;
esac


