source ~/repos/dotfiles/config/vim/plugins.vim
source ~/repos/dotfiles/config/vim/options.vim
source ~/repos/dotfiles/config/vim/keymap.vim
source ~/repos/dotfiles/config/vim/functions.vim
source ~/repos/dotfiles/config/vim/autocommands.vim
