if has('gui')
	set guioptions=!d
	set guifont=MesloLGS\ NF

	if has('win32')
		augroup gvim_startup
			autocmd!
			autocmd GUIEnter * winpos 0 0
			autocmd GUIEnter * set lines=100 columns=180
		augroup END
	endif
endif

let s:vimdir=has('win32') ? '~/vimfiles' : '~/.vim'
let s:plug_vim=expand(s:vimdir .. "/autoload/plug.vim")

let s:did_bootstrap=0
if !filereadable(s:plug_vim)
	call system("curl -fLo " .. s:plug_vim .. " --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim")
	let s:did_bootstrap=1
	execute "source " .. s:plug_vim
endif

let s:catppuccin_theme=expand(s:vimdir .. "/colors/catppuccin_mocha.vim")
if !filereadable(s:catppuccin_theme)
	call system("curl -fLo " .. s:catppuccin_theme .. " --create-dirs https://raw.githubusercontent.com/catppuccin/vim/main/colors/catppuccin_mocha.vim")
endif

source ~/repos/dotfiles/config/vim/plugins.vim
source ~/repos/dotfiles/config/vim/options.vim
source ~/repos/dotfiles/config/vim/keymap.vim
source ~/repos/dotfiles/config/vim/functions.vim
source ~/repos/dotfiles/config/vim/autocommands.vim

if s:did_bootstrap
	PlugInstall
endif

