#!/bin/bash

pgrep -x sxhkd >/dev/null || sxhkd &

ultrawide() {
	DISPLAY_NAME="DisplayPort-1"
  export RIGHT="$DISPLAY_NAME"
	~/.screenlayout/amd.sh
	bspc monitor -d 1 2 3 4 5 6 7 8 9 0
	~/.config/polybar/launch.sh kill
	~/.config/polybar/launch.sh right

}

pip-mode() {
	export LEFT="HDMI-0"
	export RIGHT="DP-4"

	~/.screenlayout/pip.sh
	# Set display from arandr saved script
	bspc monitor $RIGHT -d 1 2 3 4 5 6
	bspc monitor $LEFT -d 7 8 9 0
	# Explicitly set the monitor order to ensure DP-4 workspaces precede HDMI-0 workspaces
	bspc wm --reorder-monitors $RIGHT $LEFT
}

virtual-pip-mode() {
	# Store the focused node so we can restore it later
	FOCUSED="$(bspc query -n focused -N)"
	~/.screenlayout/amd.sh
	DISPLAY_NAME="DisplayPort-1"
	export LEFT="vir1"
	export RIGHT="vir2"
	export FHD="FHD"
	export QHD="QHD"

	# Ensure the main monitor is focused
	bspc monitor -f "$DISPLAY_NAME"
	# Configure the virtual monitors in xrandr if they are not already
	if ! xrandr --listactivemonitors | grep -q "vir"; then
		# Set the monitors with xrandr so other programs (polybar) know about the virtual displays as well
		xrandr --setmonitor "$LEFT" 2560/595x1440/340+0+0 "$DISPLAY_NAME"
		xrandr --setmonitor "$RIGHT" 2560/595x1440/340+2560+0 none

		# Force a resolution change to ensure the changes are propagated (not sure if this is needed?)
		xrandr --fb 5121x1440
		xrandr --fb 5120x1440
	fi

	# If the virtual monitors are not already configured, create them
	if ! bspc query -M --names | grep -q vir; then
		bspc wm -a "$LEFT" "2560x1440+0+0"
		bspc wm -a "$RIGHT" "2560x1440+2560+0"
		bspc wm -a "$FHD" "1920x1080+1600+180"
		bspc wm -a "$QHD" "2560x1440+1280+0"
	fi
	#
	# We don't want any top padding for the QHD monitor
	bspc config -m "$QHD" top_padding 0

	bspc monitor $LEFT -d 1 2 3
	bspc monitor $RIGHT -d 4 5 6 7
	bspc monitor $FHD -d 8
	bspc monitor $QHD -d 9
	# Put a single desktop on the physical monitor to support fullscreen
	bspc monitor $DISPLAY_NAME -d 0

	# Restore focus
	bspc node -f "$FOCUSED"

	# Explicitly reorder the monitors to ensure the workspace order is correct
	bspc wm --reorder-monitors $LEFT $RIGHT $FHD $QHD $DISPLAY_NAME
}

# Configure the screen so the is a single 2560x1440 monitor in the middle, and two 1280x1440 monitors surrounding it
virtual-triple-pip-mode() {
	DISPLAY_NAME="DisplayPort-1"
	export LEFT="vir1"
	export RIGHT="vir2"
	export MIDDLE="vir3"

	# Ensure the main monitor is focused
	bspc monitor -f "$DISPLAY_NAME"
	# Configure the virtual monitors in xrandr if they are not already
	if ! xrandr --listactivemonitors | grep -q "vir"; then
		# Set the monitors with xrandr so other programs (polybar) know about the virtual displays as well
		xrandr --setmonitor "$LEFT" 1280/297x1440/340+0+0 "$DISPLAY_NAME"
		xrandr --setmonitor "$RIGHT" 1280/298x1440/340+3840+0 none
		xrandr --setmonitor "$MIDDLE" 2560/595x1440/340+1280+0 none

		# Force a resolution change to ensure the changes are propagated (not sure if this is needed?)
		xrandr --fb 5121x1440
		xrandr --fb 5120x1440
	fi

	# If the virtual monitors are not already configured, create them
	if ! bspc query -M --names | grep -q vir; then
		bspc wm -a "$LEFT" "1280x1440+0+0"
		bspc wm -a "$MIDDLE" "2560x1440+1280+0"
		bspc wm -a "$RIGHT" "1280x1440+3840+0"
	fi
	#
	# We don't want any top padding for the QHD monitor
	bspc config -m "$MIDDLE" top_padding 0

	bspc monitor $LEFT -d 1 2 3
	bspc monitor $RIGHT -d 4 5 6
	bspc monitor $MIDDLE -d 7 8 9 0

	# Restore focus
	bspc node -f "$FOCUSED"

	# Explicitly reorder the monitors to ensure the workspace order is correct
	bspc wm --reorder-monitors $LEFT $RIGHT $MIDDLE

	# Open steam games on last workspace
	GAMES=$(fd -d 1 "appmanifest" ~/.steam/steam/steamapps -x echo '{/.}' | sed 's/[^0-9]//g')
	for game in $GAMES; do
		echo $game
		bspc rule -a steam_app_"$game" desktop=^10 state=fullscreen
	done

	# Bar
	~/.config/polybar/launch.sh kill
	~/.config/polybar/launch.sh left
	~/.config/polybar/launch.sh right
	~/.config/polybar/launch.sh vir3
}

# ultrawide
virtual-triple-pip-mode
# virtual-pip-mode
# pip

bspc config split_ratio 0.65
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

# prevent windows from stealing focus
bspc config ignore_ewmh_focus true

bspc rule -a looking-glass-client desktop=^10 state=fullscreen
bspc rule -a Pavucontrol:pavucontrol state=floating
bspc rule -a 'Virt-manager:*' state=floating
bspc rule -a 'Arandr:*' state=floating
bspc rule -a 'Blueman-manager:*' state=floating
bspc rule -a "Thunar:*" state=floating
bspc rule -a "Steam" desktop=^4

bspc config top_padding 40
bspc config window_gap 12
# Border
bspc config border_width 2
bspc config focused_border_color "#ac21c4"
bspc config normal_border_color "#073642"
bspc config active_border_color "#073642"
bspc config single_monocle false

# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/

# the firewall-applet in /etc/xdg/autostart/firewall-applet.desktop
# does not check if it is already running and will launch new instances.
# This hack just kills them all and starts a new one
pkill firewall-applet
firewall-applet &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
# ~/.config/bspwm/scripts/low_bat_notifier.sh

# Set caps = escape
setxkbmap -option caps:escape
# pgrep -x xautolock > /dev/null || xautolock -time 30 -locker "systemctl suspend" -detectsleep &

# disable screen sleeping on inactivity
xset -dpms &
xset s off &

# picom
# -b: daemon mode
picom -b --config ~/.config/picom.conf

# set the usless key left of 'z' to backtick / tilde
xmodmap -e 'keycode 94 = grave asciitilde'
