icons:
  - class_name:
      - matches: xfce4-terminal|alacritty|.*wezterm.*|st
        icon: 
        window_title:
          - tmux: 
          - htop: 
          - matches: ^(nvim|vim|vi)
            icon: 
      - matches: qutebrowser|chromium|firefox
        icon: 
        window_title:
          - contains: youtube
            icon: 
          - contains: gmail
            icon: 
          - contains: outlook
            icon: 
          - matches: (.*pull requests?|.*issues?|^opentap/|^opentap - |.*opentap/opentap).*
            icon: 
          - contains: gitlab
            icon: 
          - matches: .* - qutebrowser$
            icon: 󰄛
          - matches: .*Mozilla Firefox$
            icon: 
      - discord: ﭮ
      - Steam: 
      - Spotify: 
      - jetbrains-rider: 
      - teams-for-linux: 󰊻
      - HakuNeko: 
      - matches: ^code
        icon: 
      - matches: thunar|dolphin
        icon: 
      - matches: emacs
        icon: 
      - matches: zathura
        icon: 󰈦
      - matches: pavucontrol
        icon: 
      - matches: .*ghidra.*
        icon: 
      - matches: .*
        icon: 
