# Theming
font: JetBrainsMono Nerd Font 12
background: "#11111bd0"
color: "#cba6f7"
border: "#cba6f7"
separator: " ➜ "
border_width: 2
corner_r: 10
padding: 15 # Defaults to corner_r

# Anchor and margin
anchor: center # One of center, left, right, top, bottom, bottom-left, top-left, etc.
# Only relevant when anchor is not center
margin_right: 0
margin_bottom: 0
margin_left: 0
margin_top: 0

menu: 
  "1": { desc: "10%", cmd: "~/.config/sxhkd/scripts/backlight.sh --set 10" }
  "2": { desc: "20%", cmd: "~/.config/sxhkd/scripts/backlight.sh --set 20" }
  "3": { desc: "30%", cmd: "~/.config/sxhkd/scripts/backlight.sh --set 30" }
  "4": { desc: "40%", cmd: "~/.config/sxhkd/scripts/backlight.sh --set 40" }
  "5": { desc: "50%", cmd: "~/.config/sxhkd/scripts/backlight.sh --set 50" }
  "6": { desc: "60%", cmd: "~/.config/sxhkd/scripts/backlight.sh --set 60" }
  "7": { desc: "70%", cmd: "~/.config/sxhkd/scripts/backlight.sh --set 70" }
  "8": { desc: "80%", cmd: "~/.config/sxhkd/scripts/backlight.sh --set 80" }
  "9": { desc: "90%", cmd: "~/.config/sxhkd/scripts/backlight.sh --set 90" }
  "0": { desc: "100%", cmd: "~/.config/sxhkd/scripts/backlight.sh --set 100" }

