# Theming
font: JetBrainsMono Nerd Font 12
background: "#11111bd0"
color: "#cba6f7"
border: "#cba6f7"
separator: " ➜ "
border_width: 2
corner_r: 10
padding: 15 # Defaults to corner_r

# Anchor and margin
anchor: center # One of center, left, right, top, bottom, bottom-left, top-left, etc.
# Only relevant when anchor is not center
margin_right: 0
margin_bottom: 0
margin_left: 0
margin_top: 0

menu: 
  "q": { desc: Lock, cmd: swaylock }
  "w": { desc: Logout, cmd: pkill -x dwl }
  "e": { desc: Poweroff, cmd: systemctl poweroff }
  "r": { desc: Reboot, cmd: systemctl reboot }
  "t": { desc: Sleep, cmd: systemctl suspend }
