format = """
$hostname\
$status\
[](bg:#769ff0 fg:#eba0ac)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[ ](fg:#394260)\
\n$character"""

add_newline = true

[character] 
# The 'success_symbol' segment is being set to '➜' with the color 'bold green'
success_symbol = '[\$](bold green)' 
error_symbol = '[\$](bold red)'

[hostname]
ssh_only = true
style = "fg:#1e1e2e bg:#eba0ac"
format = "[$ssh_symbol$hostname]($style)"

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[status]
disabled = false
format = '[ $symbol $status]($style)'
style = "bg:#eba0ac fg:#1e1e2e"
pipestatus = true
map_symbol = false
pipestatus_format = '[$pipestatus => $symbol $status]($style)'
pipestatus_separator = '[ | ]($style)'

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
