#!/bin/bash
# Only show a border around the currently active window

for pid in $(pidof -x no_border_wine); do 
  if [ $pid != $$ ]; then 
    kill $pid
    echo "Killing sibling"
  fi
done

# Whenever a node is focused, remove it's border if:
# 1. it is a WINE window 
# 2. it is floating
while read -ra e; do
  added=${e[3]}
  if xprop -id "$added" | grep -q "_WINE_HWND_"; then
    if bspc query -n "$added" -T | yq '.client.state' | grep -q 'floating' ; then
      bspc config -n "$added" border_width 0
    else
      bspc config -n "$added" border_width 2
    fi
  fi
done < <(bspc subscribe node_focus)
