export DEBUGINFOD_URLS="https://debuginfod.archlinux.org/"
CC=${CC:-gcc}
export CC
export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH:$HOME/go/bin:$HOME/.cargo/bin
# add npm binaries
export PATH="$HOME/.node_modules/bin:$PATH"
export npm_config_prefix=~/.node_modules
export LANG=en_US.UTF-8
export EDITOR='vim'
export FZF_DEFAULT_OPTS='--layout=reverse'
export MANPAGER='nvim +Man! -'

# startx on login on VT 1
if [[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && [ -t 0 ]; then
  startx
fi

export KUBECONFIG=~/repos/helm-charts/charts/ks8500/.debug/output/kubeconfig.yaml
export ZSH=$HOME/.oh-my-zsh
#
# Disable omz update prompts
zstyle ':omz:update' mode disabled


# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"
# ZSH_THEME="robbyrussell"

ZSH_CUSTOM=${ZSH_CUSTOM:-$ZSH/custom}
[ -d ~/.oh-my-zsh ] || sh -c "git clone https://github.com/ohmyzsh/ohmyzsh.git $ZSH && compaudit | xargs chmod g-w,o-w $ZSH"
[ -d $ZSH_CUSTOM/themes/powerlevel10k ] || sh -c "git clone https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k"
[ -d $ZSH_CUSTOM/plugins/zsh-syntax-highlighting ] || sh -c "git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_CUSTOM/plugins/zsh-syntax-highlighting"
[ -d $ZSH_CUSTOM/plugins/zsh-autosuggestions ] || sh -c "git clone https://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions"
[ -d $ZSH_CUSTOM/plugins/zsh-z ] || sh -c "git clone https://github.com/agkozak/zsh-z $ZSH_CUSTOM/plugins/zsh-z"
[ -d $ZSH_CUSTOM/plugins/fzf-zsh-plugin ] || sh -c "git clone https://github.com/unixorn/fzf-zsh-plugin $ZSH_CUSTOM/plugins/fzf-zsh-plugin"
[ -d $ZSH_CUSTOM/plugins/fzf-tab-completion ] || sh -c "git clone https://github.com/lincheney/fzf-tab-completion $ZSH_CUSTOM/plugins/fzf-tab-completion"
source $ZSH_CUSTOM/plugins/fzf-tab-completion/zsh/fzf-zsh-completion.sh

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-syntax-highlighting zsh-autosuggestions zsh-z fzf-zsh-plugin)

source $ZSH/oh-my-zsh.sh


# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# don't nest nvim
if [ -n "$NVIM" ]; then
  if command -v nvr &> /dev/null; then
    alias nvim="nvr -l"
    export MANPAGER='nvr -l +Man! -'
    export EDITOR='nvr -l'
  fi
fi

export POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

autoload -U compinit; compinit
autoload -U +X bashcompinit && bashcompinit

alias yank='xclip -selection clipboard'
alias cd='z'
bindkey '^I' fzf_completion

my_ctags() {
  ctags -R --map-C=+.h --languages=c --c++-kinds=+p --fields=+iaS --extras=+q --sort=foldcase $*
}

vimtags() {
  ctags -R --languages=vim .
}

# vim: set et sw=2 sts=2 tw=78 ft=sh:
