# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH:$HOME/go/bin:$HOME/.cargo/bin

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor
export EDITOR='nvim'

export BAT_THEME=base16
export FZF_DEFAULT_OPTS='--layout=reverse'

export MANPAGER='nvim +Man! "+let g:auto_session_enabled = v:false"'

# opt out of autocd
unsetopt autocd

# don't nest nvim
if [ -n "$NVIM" ]; then
  if command -v nvr &> /dev/null; then
    alias nvim="nvr -l"
    export MANPAGER='nvr -l +Man! -'
    export EDITOR='nvr -l'
  fi
fi

alias yank='xclip -selection clipboard'
#
# some more ls aliases
alias ls='ls --color=tty'
alias l=ls
alias ll='ls -l'
alias la='ls -A'


ZSH_CUSTOM="$HOME/.zsh_plugins"
[ -d $ZSH_CUSTOM/themes/powerlevel10k ] || sh -c "git clone --depth 1 https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k"
[ -d $ZSH_CUSTOM/plugins/zsh-syntax-highlighting ] || sh -c "git clone --depth 1 https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_CUSTOM/plugins/zsh-syntax-highlighting"
[ -d $ZSH_CUSTOM/plugins/zsh-autosuggestions ] || sh -c "git clone --depth 1 https://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions"
[ -d $ZSH_CUSTOM/plugins/zsh-z ] || sh -c "git clone --depth 1 https://github.com/agkozak/zsh-z $ZSH_CUSTOM/plugins/zsh-z"

export ZSH_CACHE_DIR="$HOME/.cache/zsh"
# Create cache and completions dir and add to $fpath
mkdir -p "$ZSH_CACHE_DIR/completions"
(( ${fpath[(Ie)"$ZSH_CACHE_DIR/completions"]} )) || fpath=("$ZSH_CACHE_DIR/completions" $fpath)

source "$ZSH_CUSTOM/themes/powerlevel10k/powerlevel10k.zsh-theme"
source ~/.config/zsh/completion/completion.zsh
source ~/.config/zsh/completion/key-bindings.zsh

autoload -U compinit; compinit
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
