bindkey -e

alias ls='ls --color'

generate_command_shortcuts () {
  for kvp in "$@"; do
    local key="${kvp%%:*}"
    local val="${kvp#*:}"
    local funcname="zle_autogen_$key"
    source <(<< EOF
$funcname () {
  printf '%s\n\n\n' "\$($val 2>&1)"; zle redisplay;
}
zle -N $funcname
bindkey '^[$key' $funcname
EOF
)
  done
}

bindkey '\e\C-u' up-directory
generate_command_shortcuts \
  's:git -c color.ui=always status' \
  'l:ls -lh' \
  'e:eval $BUFFER'

export EDITOR='nvim'
export MANPAGER='nvim +Man! -'

fpath+=($HOME/repos/velvet/main/shell-completion/zsh)
autoload -U compinit && compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

eval "$(starship init zsh)"
eval "$(starship completions zsh)"
eval "$(zoxide init zsh)"

# Make / and . delimit words
WORDCHARS=${WORDCHARS//[\/\.\-]}

HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
# Ensure no dups in history
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
# Save history immediately instead of waiting for session to end
setopt INC_APPEND_HISTORY

# less does not properly display graphemes without this (??)
export LESSCHARSET=utf8
export PATH="$HOME/.local/share/bob/nvim-bin:$PATH:$HOME/.local/bin"
